CREATE TABLE users1 (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL_ADDRESS VARCHAR(50) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    SSN VARCHAR(50) NOT NULL UNIQUE
);
